#!/usr/bin/env bash
# Setup the project for initial use (after cloning) or reset it back to the initial (unused) state.

set -e
cd "$(dirname "$0")/.."


echo "==> Setting up / resetting project for initial use..."

script/clean --all

script/bootstrap
